#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_ILITEK2511) += ilitek2511.o
ilitek2511-objs := ilitek_main.o ilitek_platform_init.o ilitek_update.o ilitek_tool.o
