########### paramter (ref to tulip_cedarx.conf)############
[parameter]
enc_rec_ref_buf_reduce_enable = 1
ve_rx_input_buf_multiplex_enable = 0
product_mode = 3                       #3:cdr
enc_rcmode = 0                         #0:CBR
region_link_enable = 1
region_link_tex_detect_enable = 1
region_link_motion_detect_enable = 1
region_link_motion_detect_inv = 0      #[0~10], default 0, like 1: means detect every frame

capture_sample_rate = 16000
capture_bit_witdh = 16
capture_channel_cnt = 1
capture_ans_en = 1
capture_agc_en = 1
capture_aec_en = 1
aenc_type = "aac"
aenc_bitrate = 32000

recorder_vi_dev = 1
recorder_vi_virchn = 0
recorder_isp_dev = 1
recorder_cap_width = 2560
recorder_cap_height = 1440
recorder_cap_frmrate = 25
recorder_cap_format = "nv21"
recorder_vi_bufnum = 3
recorder_enable_WDR = 0
recorder_vi_stitch_mode = 1  # 0: DMA_STITCH_NONE, 1: DMA_STITCH_2IN1_LINNER, 2: DMA_STITCH_HORIZONTAL, 3: DMA_STITCH_VERTICAL
recorder_enc_chn = 0
recorder_enc_online = 1
recorder_enc_online_share_bufbum = 1
recorder_enc_isp2ve = 1
recorder_enc_ve2isp = 1
recorder_enc_type = "H.264"
recorder_enc_width = 2560
recorder_enc_height = 1440
recorder_enc_frmrate = 25
recorder_enc_bitrate = 1572864  #12582912
recorder_enc_refframelbcmode = 0  #4
recorder_rec_duration = 100
recorder_rec_file_cnt = 5
recorder_rec_file_format = "mp4"
recorder_rec_file = "/mnt/extsd/recorder"

takepic_enable = 1
takepic_online = 1          #0:offline, 1:online
takepic_interval = 5        #unit:s
takepic_thumb_enable = 0    #0:disable thumb and exif, 1:enable thumb and exif
takepic_vi_dev = 1
takepic_vi_virchn = 1
takepic_enc_chn = 8
takepic_file_cnt = 5
takepic_file = "/mnt/extsd/takepic"

preview_enable = 1
preview_mode = 0            #0:rtsp, 1:hwdisplay
preview_rtsp_id = 0
preview_rtsp_net_type = 3   #RTSP Network type, 0: "lo", 1: "eth0", 2: "br0", 3: "wlan0"
preview_disp_x = 0
preview_disp_y = 0
preview_disp_width = 480
preview_disp_height = 640
preview_disp_dev = "lcd"
preview_vi_dev = 5
preview_vi_virchn = 0
preview_isp_dev = 1
preview_cap_width = 640
preview_cap_height = 480
preview_cap_frmrate = 25
preview_cap_format = "nv21"
preview_vi_bufnum = 3
preview_enable_WDR = 0
preview_vi_stitch_mode = 1  # 0: DMA_STITCH_NONE, 1: DMA_STITCH_2IN1_LINNER, 2: DMA_STITCH_HORIZONTAL, 3: DMA_STITCH_VERTICAL
preview_enc_chn = 1
preview_enc_online = 1
preview_enc_online_share_bufbum = 1
preview_enc_isp2ve = 1
preview_enc_ve2isp = 0
preview_enc_type = "H.264"
preview_enc_width = 640
preview_enc_height = 480
preview_enc_frmrate = 25
preview_enc_bitrate = 262144  #2097152
preview_enc_refframelbcmode = 0  #4

test_duration = 0
