########### paramter (ref to tulip_cedarx.conf)############
[parameter]
pcm_in_path = "/mnt/extsd/tmp_in_ai_pcm"
pcm_ref_path = "/mnt/extsd/tmp_ref_ai_pcm"
pcm_out_path = "/mnt/extsd/tmp_out_ai.pcm"
pcm_sample_rate = 16000
pcm_channel_cnt = 1
pcm_bit_width = 16
ref_pcm_skip = 0 #unit:ms
