########### paramter (ref to tulip_cedarx.conf)############
[parameter]
capture_width = 1920
capture_height = 1080
display_x = 0
display_y = 0
display_width = 640
display_height = 360
layer_num = 0
isp_dev = 2
vipp_dev = 2
pic_format = "nv21"
frame_rate = 20

capture_width2 = 1920
capture_height2 = 1080
display_x2 = 640
display_y2 = 0
display_width2 = 640
display_height2 = 360
layer_num2 = 1
isp_dev2 = 0
vipp_dev2 = 0
pic_format2 = "nv21"
frame_rate2 = 20

npu_isp_dev = 2
npu_vipp_dev = 6
npu_capture_width = 1920
npu_capture_height = 1080
npu_model_file = "/mnt/sdcard/pix_allwinner_facekit_v1.4.bin"
npu_pic_format = "nv21"
npu_frame_rate = 20

npu_isp_dev_1 = 0
npu_vipp_dev_1 = 4
npu_capture_width_1 = 1920
npu_capture_height_1 = 1080
npu_model_file_1 = "/mnt/sdcard/pix_allwinner_facekit_v1.4.bin"
npu_pic_format_1 = "nv21"
npu_frame_rate_1 = 20

person_pic_ir_file_1 = "/mnt/sdcard/sample_mpp/sample_facekit_demo/1920_1080_ir.yuv"
person_pic_rgb_file_1 = "/mnt/sdcard/sample_mpp/sample_facekit_demo/1920_1080_rgb.yuv"
person_pic_id1 = 1
person_pic_name1 = "person1"
person_pic_width1 = 1920
person_pic_height1 = 1080

# disp_type is lcd, hdmi, cvbs
disp_type = "lcd"
test_duration = 0      #unit:s
