########### paramter (ref to tulip_cedarx.conf)############
[parameter]
src_file = "/mnt/extsd/test.yuv"
src_width = 1920
src_height = 1080
dst_file = "/mnt/extsd/test.raw"
dst_width = 1920
dst_height = 1080

####yuv_src_pixfmt just support yu12(yuv420p), yv12(yvu420p), nv12(yuv420sp), nv21(yvu420sp), yu16(yuv422p), nv16(yuv422sp), nv61(yvu422sp), argb in sample code at now####
src_pixfmt = "nv21"

#color space: jpeg, rec709, rec709_part_range
color_space = "rec709_part_range"

######encoder can be: "H.264"  "H.265"  "MJPEG". 
encoder = "H.264"

#####use pfrofile, for h264: 0 -> base; 1 -> main; 2 -> high(suggested);
#####              for h265: 0 -> main(suggested); 1 -> main10; 2 -> sti11
profile = 2

framerate = 20     # fps
bitrate = 2000000  # bps

#encode rotate, 0, 90, 180, 270, clockwise.
rotate = 0

#rc_mode for H264/H265 0:CBR  1:VBR  2:FIXQP  3:QPMAP
rc_mode = 1
#gop mode is 0:NormalP, 1:DualP, 2:SmartP
gop_mode = 0
#H265 gop_size should be [1, 63]
gop_size = 2
#product_mode: 0:static ipc, 1:moving ipc, 2: doorbell, 3:cdr, 4:sdv, 5:projection, 6:UAV(Unmanned Aerial Vehicle)
product_mode = 0
#key_frame_interval should be integral multiple of gop_size
key_frame_interval = 50

######################### VBR/CBR #########################
#qp_range should be note that init_qp just make sense in vbr
init_qp = 37
min_i_qp = 10
max_i_qp = 45
min_p_qp = 10
max_p_qp = 45

######################### FixQp #########################
i_qp = 10
p_qp = 45

######################### VBR #########################
#moving_th is the threshold of MAD in mb16x16, range[0, 31]
moving_th = 20
#quality is the coef of bits in static P frame, range[1, 20]
quality = 10
#p_bits_coef is the coef of bits in move P frame, range[1, 50]
p_bits_coef = 10
#i_bits_coef is the coef of bits in I frame, range[1, 20]
i_bits_coef = 10

enable_gdc = 0
gdc_mirror = 0
# LDC:0 LDC_Pro:1 Pano180:2 Pano360:3 Normal:4 Fish2Wide:5 Perspective:6 BirdsEye:7
gdc_warp_mode = 0
# Top:0 Wall:1 Bottom:2
gdc_mount_type = 0
gdc_LDC_Pro_lut_bin = ""

test_duration = 30 # unit is s
front_cut_frame_num = 0
back_cut_frame_num = 0
read_frame_num = 100
