########### paramter (ref to tulip_cedarx.conf)############
[parameter]

stream_0_vi_dev = 0
stream_0_isp_dev = 0
stream_0_cap_width = 1920
stream_0_cap_height = 1080
stream_0_cap_frmrate = 20
stream_0_cap_format = "nv21"
stream_0_vi_bufnum = 3
stream_0_enable_WDR = 0
stream_0_enc_online = 0
stream_0_enc_online_share_bufbum = 2
stream_0_enc_type = "H.265"
stream_0_enc_width = 1920
stream_0_enc_height = 1080
stream_0_enc_frmrate = 20
stream_0_enc_bitrate = 2097152
stream_0_enc_rcmode = 1
stream_0_encpp_enable = 1
stream_0_enc_ve_ref_frame_lbc_mode = 0         #0:default(1.5x), 1:1.5x, 2:2.0x, 3:2.5x, 4:no lossy
stream_0_enc_key_frame_interval = 100

stream_1_vi_dev = 4
stream_1_isp_dev = 0
stream_1_cap_width = 1280
stream_1_cap_height = 720
stream_1_cap_frmrate = 20
stream_1_cap_format = "nv21"
stream_1_vi_bufnum = 3
stream_1_enable_WDR = 0
stream_1_enc_online = 0
stream_1_enc_online_share_bufbum = 2
stream_1_enc_type = "H.264"
stream_1_enc_width = 1280
stream_1_enc_height = 720
stream_1_enc_frmrate = 20
stream_1_enc_bitrate = 2097152
stream_1_enc_rcmode = 1
stream_1_encpp_enable = 1
stream_1_enc_ve_ref_frame_lbc_mode = 0
stream_1_enc_key_frame_interval = 100

stream_2_vi_dev = 8
stream_2_isp_dev = 0
stream_2_cap_width = 640
stream_2_cap_height = 360
stream_2_cap_frmrate = 20
stream_2_cap_format = "nv21"
stream_2_vi_bufnum = 3
stream_2_enable_WDR = 0
stream_2_enc_online = 0
stream_2_enc_online_share_bufbum = 2
stream_2_enc_type = "H.265"
stream_2_enc_width = 640
stream_2_enc_height = 360
stream_2_enc_frmrate = 20
stream_2_enc_bitrate = 2097152
stream_2_enc_rcmode = 1
stream_2_encpp_enable = 1
stream_2_enc_ve_ref_frame_lbc_mode = 0
stream_2_enc_key_frame_interval = 100

stream_num = 3
test_duration = 20
video_file_max_cnt = 3
video_file_max_duration = 20
video_dst_file = "/mnt/extsd/test.mp4"

