########### paramter (ref to tulip_cedarx.conf)############
[parameter]
uvc_dev = 1

vin_dev = 0

isp_dev = 0

#some encode parameters
enc_bit_rate = 4194304 # 4M(4194304) 8M(8388608) for mjpeg and h264

enable_encode_online = 1 #only v85x support

enable_uac = 0
uac_dev = "hw:2,0"
uac_sample_rate = 16000
uac_chn_cnt = 1
uac_bit_width = 16
uac_ai_gain = 80
aec_en = 0
ans_en = 0
ans_mode = 0
agc_en = 0
