########### paramter (ref to tulip_cedarx.conf)############
[parameter]

# vipp dev id.
dev_num = 0
isp_dev = 0
src_width = 1920
src_height = 1080
vi_stitch_mode = 0	# 0: DMA_STITCH_NONE, 1: DMA_STITCH_2IN1_LINNER, 2: DMA_STITCH_HORIZONTAL, 3: DMA_STITCH_VERTICAL
tdm_spdn_en = 0		# 0: default, disable, 1: enable tdm speed down, must be enable CONFIG_SUPPORT_ISP_TDM for kernel
mipi_pixel_num = 0	# 0: MIPI_ONE_PIXEL, 1: MIPI_TWO_PIXEL(only mipi 4lane can set MIPI_TWO_PIXEL)

#fps
frame_rate = 20

# Normal: nv21(yvu420sp), yu12(yuv420p), yv12, nv12
# LBC: aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_1_0x
src_format = "aw_lbc_2_0x"

# only for jpeg
# for H264/H265, only output yuv420 is supported (regardless of setting).
# test conditions: yuv sensor
# 0:same as input(default), 1:yuv420, 2:yuv444, 3: yuv422
# support downsample:
# input yuv420 -> output yuv420
# input yuv422 -> output yuv422/420
# input yuv444 -> output yuv444/422/420
output_format = "same_as_input"

#color space: jpeg, rec709, rec709_part_range
color_space = "jpeg"

#drop frame num, offline: vipp drop frm, online: ve drop frm.
drop_frm_num = 0

encode_rotate = 0   #encode rotate, 0, 90, 180, 270, clockwise.
mirror = 0          #encode mirror, 0: disable, 1: enable

crop_en = 0         #0: disable, 1: enable
crop_rect_x = 0
crop_rect_y = 0
crop_rect_w = 1280
crop_rect_h = 720

thumb_width = 320
thumb_height = 240
thumb_quality = 60
thumb_save_to_file_enable = 0     # 0: not save thumbnail file 1: save thumbnail file

encpp_enable = 1

### Expand feature ###
# 0: No photo mode, 1: one shot mode, 2: continuous shooting mode.
take_picture_mode = 1

take_picture_num = 5
take_picture_interval = 500  #unit: ms

jpeg_width = 1920
jpeg_height = 1080

# save path of the jpeg picture
# for single shot mode, pic[n][0]
# for continuous shooting mode, pic[0][n]
store_dir = "/mnt/extsd"

