########### paramter (ref to tulip_cedarx.conf)############
[parameter]
pcm_src_path = "/mnt/extsd/sample_aoref_16000_ch1_bit16_aec_30s.wav"
pcm_dst_path = "/mnt/extsd/ai_cap.wav"
pcm_aec_path = "/mnt/extsd/ai_aec.wav"
pcm_sample_rate = 16000
mic_num = 1 #1 or 2
pcm_channel_cnt = 1
pcm_bit_width = 16
pcm_frame_size = 1024
ai_volume = 80
ao_volume = 80
aec_en = 1
aec_ref_delay = 0 #unit:ms
aec_nlp_mode = 1 #0,1,2, kAecNlpConservative, kAecNlpModerate, kAecNlpAggressive
aec_bypass = 0
ans_en = 1
ans_mode = 1
agc_en = 1
agc_target_db = 0
agc_max_gain_db = 30
add_wav_header = 1
