/*
* Copyright (c) 2024-2030 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __PLATFORM_IRQ_SUN20IW3_H__
#define __PLATFORM_IRQ_SUN20IW3_H__

#ifdef CONFIG_ARCH_RISCV_INTERRUPT_NEST
#define IRQSTACK_BOTTOM_MAGIC	(0x55555555)

#define NEST_PLAT_ROOT_IC_REG_BASE_ADDR (0x30800000UL)
#define PLAT_CLIC_CLICINTCTLBITS	(3)

#define CLIC_INT_REG_ADDR_INTERVAL 	(0x4)
#define CLIC_INT_X_IP_REG_OFF(id) 	(0x1000 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))
#define CLIC_INT_X_IE_REG_OFF(id) 	(0x1001 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))
#define CLIC_INT_X_ATTR_REG_OFF(id)	(0x1002 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))
#define CLIC_INT_X_CTRL_REG_OFF(id) 	(0x1003 + ((id) * CLIC_INT_REG_ADDR_INTERVAL))

#define CLIC_MINTTHRESH_REG_OFF 0x08

#define TRIGGER_TYPE_SHIFT 1
#define TRIGGER_TYPE_BIT_MASK (0x3 << TRIGGER_TYPE_SHIFT)

#if CONFIG_SET_CLICINTCTL_NLBITS > PLAT_CLIC_CLICINTCTLBITS
#define CLICINTCTL_NLBITS		(PLAT_CLIC_CLICINTCTLBITS)
#elif CONFIG_SET_CLICINTCTL_NLBITS >= 0
#define CLICINTCTL_NLBITS		(CONFIG_SET_CLICINTCTL_NLBITS)
#else
#define CLICINTCTL_NLBITS		(0)
#endif
#endif /* CONFIG_ARCH_RISCV_INTERRUPT_NEST */

#endif /* __PLATFORM_IRQ_SUN20IW3_H__ */
