########### paramter (ref to tulip_cedarx.conf)############
[parameter]

online_en = 0                  #0:disable, 1:enable
online_share_buf_num = 2       #only for online enable, 1:one buf, 2:two buf

vipp_id = 0
wdr_en = 0
src_width  = 1920
src_height = 1080
vi_buffer_num = 3

# Normal: nv21(yvu420sp), yu12(yuv420p), yv12, nv12
# LBC: aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_1_0x
src_pixfmt = "nv21"

venc_ch_id = 0
video_framerate = 20
video_bitrate = 1572864   #5M:5242880, 4M:4194304, 3M:3145728, 2M:2097152, 1.5M:1572864, 1M:1048576
video_width  = 1920
video_height = 1080
video_encoder = "H.264"      #H.264; H.265; MJPEG

enable_gdc = 1           #Enable GDC, 0:disable(default), 1:enable.
enable_gdc_zoom = 1      #if enable gdc, Enable GDC zoom, 0:disable(default), 1:enable.

dynamic_crop_en = 0      #0: disable, 1: enable

video_dst_file = "/mnt/extsd/test.raw"
test_duration = 20   #total test time. unit:s, 0 means infinite.

