########### paramter (ref to tulip_cedarx.conf)############
[parameter]
pcm_sample_rate = 16000
pcm_channel_cnt = 1
pcm_bit_width = 16
pcm_frame_size = 1024
aec_en = 1
ans_en = 1
ans_mode = 1
agc_en = 1
agc_float_target_db = 0
agc_float_max_gain_db = 30

enable_uac1_in = 1
enable_uac1_out = 1
