########### paramter (ref to tulip_cedarx.conf)############
[parameter]
pcm_file_path = "/tmp/test/wav/sample_ai_pcm.wav"
pcm_sample_rate = 16000
mic_num = 1 #1 or 2
pcm_channel_cnt = 1
pcm_bit_width = 16
pcm_frame_size = 1024
pcm_cap_duration = 10
pcm_ai_gain = 100
ans_en = 0
ans_mode = 3
agc_en = 0
agc_target_db = 0
agc_max_gain_db = 30
