########### paramter (ref to tulip_cedarx.conf)############
[parameter]
src_file = "/mnt/extsd/test.mp4"
#src_type has two values: 0:fd, 1:url, e.g., "http://downsc.chinaz.net/files/download/sound1/201206/1638.mp3"
src_type = 0
seek_position = 0
dev_volume = 90
agc_en = 0
agc_target_db = 0
agc_max_gain_db = 30
