########### paramter (ref to tulip_cedarx.conf)############
[parameter]
# `ls /dev/video*` to check uvc_device name.
uvc_dev = "/dev/video1" #empty string means disable uvc_dev.
uvc_capture_colorspace = "rec709" #jpeg, rec709, rec709_part_range
uvc_capture_framerate = 20
uvc_capture_width = 1280
uvc_capture_height = 720
uvc_capture_videobufcnt = 2
uvc_capture_maxframesize_ratio = 0.2 # 0 means use default value.
vdec_extra_frame_num = 1 #-1 means to use number written in cedarx.conf.
vdec_pixel_format = nv12 #nv12, nv21
vdec_sub_ratio = 1 #0:disable, 1:1/2, 2:1/4, 3:1/8
uvc_display_rotate = 90 #0, 90, 180, 270
uvc_display_x = 0
uvc_display_y = 0
uvc_display_width = 480 #0 means not display.
uvc_display_height = 854

isp_color_space = "rec709" #jpeg, rec709, rec709_part_range
isp_capture_framerate = 30
vipp_dev = 0 #-1 means disable vipp.
vipp_pixel_format = nv12 #nv12, nv21, lbc20x, lbc25x
vipp_capture_width = 1280
vipp_capture_height = 720
vipp_buf_num = 3
sub_vipp_dev = 4
sub_vipp_pixel_format = nv12 #nv12, nv21, lbc20x, lbc25x
sub_vipp_capture_width = 960
sub_vipp_capture_height = 540
sub_vipp_buf_num = 3
sub_vipp_display_rotate = 90 #0, 90, 180, 270
sub_vipp_display_x = 0
sub_vipp_display_y = 0
sub_vipp_display_width = 480 #0 means not display.
sub_vipp_display_height = 854

preview_source = 1 #1:preview vipp, 0:preview uvc
preview_switch_interval = 10 #unit:s, 0 means not switch.

venc_type = "h264" #h264, h265, mjpeg, none
#rc_mode for H264/H265 0:CBR  1:VBR  2:FIXQP(only for debug)  3:ABR(not support)
rc_mode = 1
vbr_opt_en = 1        #0: old vbr bitrate control, 1:new vbr bitrate control
vbr_opt_rc_priority = 3   #only for vbr opt, balance bitrate and quality, 0:quality priority, 1:bitrate priority, 2:avg bitrate first, 3:instantaneous bitrate first
vbr_opt_rc_qualitylevel = 0   #only for vbr opt, balance bitrate and quality, 0:quality low level, 1:quality middle level, 2:quality high level

uvc_key_frame_interval = 60
uvc_video_bitrate = 1048576
uvc_encode_rotate = 90 #0, 90, 180, 270

vipp_key_frame_interval = 90
vipp_video_bitrate = 2097152
vipp_encode_rotate = 90 #0, 90, 180, 270
vipp_crop_x = 0
vipp_crop_y = 0
vipp_crop_width = 0 #0 means disable crop
vipp_crop_height = 720
vipp_encode_width = 1280
vipp_encode_height = 720
vipp_encode_sharp_en = 1
vipp_isp2ve_link_en = 1
vipp_ve2isp_link_en = 1
vipp_region_link_enable = 1
vipp_region_link_tex_detect_enable = 1
vipp_region_link_motion_detect_enable = 1
vipp_region_link_motion_detect_interval = 0 # [0~10], default 0, like 1: means detect every frame

venc_file_path = "/mnt/extsd/video.h264" #empty string means need not to write file.
venc_file_duration = 60 #unit:s, 0 menas don't switch file.
venc_file_num = 10
rtsp_net_type = 3 #RTSP Network type, 0: "lo", 1: "eth0", 2: "br0", 3: "wlan0"
rtsp_id = -1 #-1:disable rtsp

sample_rate = 16000
ai_volume = 100
mic_num = 1 #0 means disable audio capture
aec_en = 1
ans_en = 1
agc_en = 1

aenc_type = "aac" #aac, pcm, none.
aenc_attachAACHeader = 1
aenc_file_path = "/mnt/extsd/audio.aac" #empty string means need to write file.
aenc_file_duration = 60 #unit:s, 0 menas don't switch file.
aenc_file_num = 10

test_duration = 90 #unit:s. 0 means infinite. ctrl+c quit.

