########### paramter (ref to sample_uvcout.conf)############
[parameter]

# config for model detect and track
detect_vi_mod_id = 16
detect_vi_dev_id = 8
detect_vi_chn_id = 0

detect_vi_width = 640
detect_vi_height = 360
detect_vi_framerat = 15

detect_npu_width = 640
detect_npu_height = 360
detect_npu_framerat = 15
nbg_file_path = "./face_detection_v5.0.1_beta"

# config for venc stream process
stream_vi_mod_id = 16
stream_vi_dev_id = 0
stream_vi_chn_id = 0
stream_vi_width = 1280
stream_vi_height = 720
stream_vi_framerat = 30

stream_ven_mod_id = 8
stream_ven_dev_id = 0
stream_ven_chn_id = 0
stream_ven_width = 1280
stream_ven_height = 720
stream_ven_framerat = 30
stream_ven_encode_type = "H.264" #96 #h264
stream_ven_encode_bitrate = 8000000

# config for uvc
uvc_dev = 2
