########### paramter (ref to tulip_cedarx.conf)############
[parameter]
src_file = "/mnt/extsd/test.mp4"
dst_file = "/mnt/extsd/resize.raw"
encode_type = "h264" #h264, h265
dst_width = 1280
dst_height = 720
rotation = 0 #90, 180, 270
bitrate = 2 #unit:Mbps
key_frame_interval = 100
