########### paramter (ref to tulip_cedarx.conf)############
[parameter]
src_file = "/mnt/extsd/1080p.mp4"
seek_position = 0
test_duration = 0
vdec_pixel_format = "nv12" #yv12, nv12, nv21
display_x = 0
display_y = 0
display_width = 480
display_height = 640
#add more frame number to vdeclib. -1:use default value written in config file. >=0: use this value instead of config file.
vdec_ExtraFrameNum = -1
voChn_FrameRate = 0 #0:no limit, >0:voChn use this frameRate to select frame to display.
#VE Freq, 0: 300MHz(default), 400MHz
ve_freq = 0
