########### paramter (ref to tulip_cedarx.conf)############
[parameter]

online_en = 0  #0:disable, 1:enable
online_share_buf_num = 2  #only for online enable, 1:one buf, 2:two buf

src_pixfmt = "nv21"       #Normal: nv21(yvu420sp), yu12(yuv420p), yv12, nv12, LBC: aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_1_0x
video_encoder = "H.264"   #H.264; H.265

vipp_index = 0
vipp_width = 1920
vipp_height = 1080
vipp_frame_rate = 20
video_frame_rate = 20
video_bitrate = 12 #unit:Mbps.

timelapse = 200000 #unit:us

video_file_path = "/mnt/extsd/timelapse.mp4"
video_duration = 10 #unit:s
