########### paramter (ref to tulip_cedarx.conf)############
[parameter]
demo_aiisp_lut_nbg_file_path = "/mnt/extsd/gamma_1080.nb"
demo_aiisp_nbg_file_path = "/mnt/extsd/FW100A12W0S00.nb"
demo_aiisp_model_version = 0
demo_aiisp_width = 1920
demo_aiisp_height = 1080
demo_aiisp_tdm_rxbuf_num = 5
demo_aiisp_mode = 0
demo_aiisp_reserve0 = 0
demo_aiisp_reserve1 = 0
demo_aiisp_reserve2 = 0
demo_aiisp_frame_rate = 10
demo_aiisp_save_after_frame = 0
demo_aiisp_input_file = "/mnt/extsd/input.raw"
demo_aiisp_output_file = "/mnt/extsd/output.raw"
