########### paramter (ref to tulip_cedarx.conf)############
[parameter]
main_vipp_width = 1920
main_vipp_height = 1080
sub_vipp_width = 640
sub_vipp_height = 360
# pic_format is yu12, yv12, nv21, nv12, lbc20x, lbc25x
main_pic_format = lbc25x
sub_pic_format = nv21
display_width = 480 #display_width or display_height = 0 means disable preview.
display_height = 270
frame_rate = 30
#encode_type is h264, h265, mjpeg
encode_type = h264
# audio encode type : aac, mp3.  means no audio.
audio_encode_type =
main_encode_width = 1920
main_encode_height = 1080
main_encode_bitrate = 6    # Mbit
main_encode_online = 0 #1:use online, 0:use offline.
main_encode_online_sharebufnum = 2
sub_encode_width = 640 #sub_encode_width or sub_encode_height = 0 means disable sub encode.
sub_encode_height = 360
sub_encode_bitrate = 2    # Mbit

segment_folder = "/mnt/extsd/sample_RecordSwitchFileNormal_Files"
segment_count = 3
#segment file method: by time or by size
segment_method = time   #time or size.
segment_duration = 60	#unit:s
segment_size = 100 #unit: MByte

