########### paramter (ref to tulip_cedarx.conf)############
[parameter]
src_width = 2048
src_height = 2048
# nv21 or nv12
src_fmt = "nv21"
src_pic = "./Normal/2048x2048_nv21_fisheye_.yuv"

dst_width = 2048
dst_height = 2048
# nv21 or nv12
dst_fmt = "nv21"
dst_pic = "/mnt/extsd/test.yuv"

# LDC:0 LDC_Pro:1 Pano180:2 Pano360:3 Normal:4 Fish2Wide:5 Perspective:6 BirdsEye:7
gdc_warp_type = 4
# Top:0 Wall:1 Bottom:2
gdc_mount_type = 1
gdc_mirror = 0
gdc_ldc_pro_lut_bin =

