########### paramter (ref to sample_uvcout.conf)############
[parameter]

# config for person detect
detect_vi_mod_id = 16
detect_vi_dev_id = 8
detect_vi_chn_id = 0

# person detect can support 384 * 224 only
detect_vi_width = 384
detect_vi_height = 224
detect_vi_framerat = 30

detect_npu_width = 384
detect_npu_height = 224
detect_npu_framerat = 30
nbg_file_path = "./3.0.8"

# config for venc stream process
stream_vi_mod_id = 16
stream_vi_dev_id = 0
stream_vi_chn_id = 0
stream_vi_width = 1280
stream_vi_height = 720
stream_vi_framerat = 30

stream_ven_mod_id = 8
stream_ven_dev_id = 0
stream_ven_chn_id = 0
stream_ven_width = 1280
stream_ven_height = 720
stream_ven_framerat = 30
stream_ven_encode_type = "H.264"  #h264
stream_ven_encode_bitrate = 8000000

# monitor config
monitor_mode = 2  # 1:CROSS_WORK_MODE_LINE, 2:CROSS_WORK_MODE_RECT
#rect
rect0_x0 = 520
rect0_y0 = 301
rect0_x1 = 385
rect0_y1 = 821
rect0_x2 = 1382
rect0_y2 = 896
rect0_x3 = 1680
rect0_y3 = 250
#line
line0_x0 = 820
line0_y0 = 201
line0_x1 = 785
line0_y1 = 821

# config for uvc
uvc_dev = 2
