########### paramter (ref to tulip_cedarx.conf)############
[parameter]
src_file = "/mnt/extsd/1080p.mp4"
vdec_pixel_format = "nv12" #yv12, nv12, nv21
vdec_output_max_width = 0 #0 means not limit.
vdec_output_max_height = 0
rotation = 0 #clock wise: 0:0, 1:90, 2:180, 3:270
#add more frame number to vdeclib. -1:use default value written in config file. >=0: use this value instead of config file.
vdec_ExtraFrameNum = -1
layer_id = 0 #-1:not use video layer.
display_x = 0
display_y = 0
display_width = 640
display_height = 360
voChn_FrameRate = 0 #0:no limit, >0:voChn use this frameRate to select frame to display.
forbid_audio = 0
audio_volume = 100 # scope:[0, 100]
video_stream_index = 0 #select video stream index, from 0.
audio_stream_index = 0 #select audio stream index, from 0.
seek_position = 0 #unit:ms
vps = 1 # vps scope:[0.5, 4]
loop = 0 #0:not loop, >0: loop play count, -1: loop infinitely
ve_freq = 0 #VE Freq, unit:MHz, 0: default
test_duration = 0 #unit:s, 0:not limit,

