########### paramter (ref to tulip_cedarx.conf)############
[parameter]
width = 1920
height = 1080
pic_format = "nv21"            # yu12,yv12,nv21,nv12; aw_lbc_2_0x,aw_lbc_2_5x,aw_lbc_1_5x,aw_lbc_1_0x
framerate = 20
bitrate = 1048576
encoder_type = "H.264"

bitmap_format = "ARGB8888"     # ARGB8888, ARGB1555
overlay_x = 32
overlay_y = 32

inv_col_en = 1
inv_col_mode = 3
inv_col_lum_thresh = 60

output_file_path = "/mnt/extsd/test.raw"

test_duration = 20   #unit:s

