########### paramter (ref to tulip_cedarx.conf)############
[parameter]
# `ls /dev/video*` to check uvc_device name.
dev_name = /dev/video1
# `cat /proc/asound/cards` to check uac_device name.
uac_dev_name = "hw:UVCUAC1" #hw:UAC1Gadget, hw:Camera, hw:UVCUAC1
# pic_format is UVC_YUY2, UVC_NV12, UVC_H264, UVC_MJPEG
pic_format = UVC_MJPEG
capture_videobufcnt = 2
capture_width = 1280
capture_height = 720
capture_framerate = 20
capture_maxframesize_ratio = 0 # 0 means use default value.
vdec_extra_frame_num = 2 #-1 means to use number written in cedarx.conf.
display_main_x = 0
display_main_y = 0
display_main_width = 320 #0 means not display.
display_main_height = 240
venc_type = "h264" #h264, h265, mjpeg, none
venc_file_path = "/mnt/extsd/uvc_host.h264"
color_space = "jpeg" #jpeg, rec709, rec709_part_range
key_frame_interval = 100
#product_mode: 0:static ipc, 1:moving ipc, 2: doorbell, 3:cdr, 4:sdv, 5:projection, 6:UAV(Unmanned Aerial Vehicle)
product_mode = 0
#rc_mode for H264/H265 0:CBR  1:VBR  2:FIXQP(only for debug)  3:ABR(not support)
rc_mode = 1
vbr_opt_en = 1        #0: old vbr bitrate control, 1:new vbr bitrate control
vbr_opt_rc_priority = 3   #only for vbr opt, balance bitrate and quality, 0:quality priority, 1:bitrate priority, 2:avg bitrate first, 3:instantaneous bitrate first
vbr_opt_rc_qualitylevel = 0   #only for vbr opt, balance bitrate and quality, 0:quality low level, 1:quality middle level, 2:quality high level
video_bitrate = 2097152
test_frame_count = 0 #0 stand for infinite.
uac_in = 1 #host receives pcm from uac, plays locally.
uac_in_chns = 1 #host can config pcm channel number to device.
ao_volume = 90
uac_out = 1 #host captures pcm locally, sends to uac.
uac_out_period_size = 160
uac_out_start_threshold_multiple = 4
sample_rate = 16000
ai_periodsize = 320
ai_volume = 100
mic_num = 1
aec_en = 1
ans_en = 1
agc_en = 1
