########### paramter (ref to tulip_cedarx.conf)############
[parameter]
preview_width = 640
preview_height = 360
preview_frame_rate = 20
preview_frame_num = 5
preview_pic_format = nv21 # pic_format is yu12, yv12, nv21, nv12, nv61, nv16
preview_mirror = 0 #0: no mirror ratation, 1: horizonta mirror rotation, 2: vertical mirror rotation
preview_rotation = 0
display_frame_rate = 0
disp_width = 640
disp_height = 360
keep_render = 0 #1:keep display frame when change preview vipp0 to capture vipp1. 0: not display.

capture_width = 1920
capture_height = 1080
capture_frame_rate = 20
capture_frame_num = 3
capture_pic_format = nv21 # pic_format is yu12, yv12, nv21, nv12, nv61, nv16, lbc2.0, lbc2.5
capture_lost_frame_cnt = 3

digital_zoom = 0 # 0~10, show_area=width*10/(10+digital_zoom)

take_photo_times = 1 #test taking_photo times.
keep_jpeg_encoder = 1
jpeg_width = 1920
jpeg_height = 1080
jpeg_quality = 90
jpeg_thumb_width = 480
jpeg_thumb_height = 270
jpeg_thumb_quality = 80
jpeg_num = 1 # picture numbers in one take_photo. 0:not take picture, 1:take one picture, >1:take continuous pictures
jpeg_interval = 100  #unit:ms, 0 indicate take every frame to encode.
jpeg_folder = "/mnt/extsd/sample_Camera_LargePhoto_Files"

test_duration = 10 #unit:s
