########### paramter (ref to tulip_cedarx.conf)############
[parameter]

#Online
online_en = 0  #0:disable, 1:enable
online_share_buf_num = 2  #only for online enable, 1:one buf, 2:two buf

#vipp dev
vipp_id = 0

#vipp wdr setting, 1:enable, 0:disable(default)
wdr_en = 0

#drop frame num, both vipp and venc can drop frm.
vi_drop_frm_num = 0
venc_drop_frm_num = 0

##### 1280x720->720p, 1920x1080->1080p, 2560×1440->2k, 3840x2160->4k, 7680x4320->8k
src_width  = 1920
src_height = 1080

src_framerate = 20

vi_buffer_num = 4

#Normal: nv21(yvu420sp), yu12(yuv420p), yv12, nv12
#LBC: aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_1_0x
src_pixfmt = "nv21"

#color space: jpeg, rec709, rec709_part_range
color_space = "rec709"

#venc dev channel id.
venc_ch_id = 0

video_dst_file = "/mnt/extsd/test.mp4"

add_repair_info = 0 #if add repair info for mp4 repair.
frmsTag_backup_interval = 100000 #unit:us, for mp4 repair

dst_file_max_cnt = 3       #max file number permited.
video_duration = 60         #per output media file time. unit:s, 0 means one file.

video_framerate = 20
video_bitrate = 2097152

##### 1280x720->720p, 1920x1080->1080p, 2304x1296->3M, 2560×1440->2k, 3840x2160->4k, 7680x4320->8k
video_width  = 1920
video_height = 1080

#H.264; H.265; MJPEG
video_encoder = "H.264"

#####use pfrofile, for h264: 0 -> base; 1 -> main; 2 -> high(suggested);
#####              for h265: 0 -> main(suggested); 1 -> main10; 2 -> sti11 
profile = 2

#LBC: aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_no_lossy
ve_ref_lbc_mode = "aw_lbc_1_5x"

#product_mode: 0:static ipc, 1:moving ipc, 2: doorbell, 3:cdr, 4:sdv, 5:projection, 6:UAV(Unmanned Aerial Vehicle)
product_mode = 0

#key frame interval, 0:=frameRate, >0:interval
key_frame_interval = 100

vbr_opt_en = 0        #0: old vbr bitrate control, 1:new vbr bitrate control

#rc_mode for H264/H265 0:CBR  1:VBR  2:FIXQP(only for debug)  3:ABR(not support)
rc_mode = 1

#gop mode is 0:NormalP(only support normalP)
gop_mode = 0

#H265 gop_size should be [1, 63]
gop_size = 2

#config vbvBufferSize and threshSize, unit:Byte/s
vbvBufferSize = 0  #0:middleware decide itself, >0:app decide. suggest: 933882(1.5Mbps@20fps)
vbvThreshSize = 0  #0:middleware decide itself, >0:app decide. suggest: 147450(1.5Mbps@20fps)

#crop config
crop_en = 0  #0: disable, 1: enable
crop_rect_x = 0
crop_rect_y = 0
crop_rect_w = 1280
crop_rect_h = 720

vui_timing_info_present_flag = 0

encpp_enable = 1

isp_ve_linkage_enable = 1

ve_rec_ref_buf_reduce_enable = 0

#sei
sei_enable = 2 #-1:disable, 0:FollowShellSet, 1:enable, 2:ignore
sei_data_isp = 1
sei_data_vipp = 0
sei_data_venc = 1
sei_frame_interval_ispLevel1 = 5
sei_frame_interval_ispLevel2 = 20
sei_frame_interval_ispLevel3 = 200
sei_frame_interval_vipp = 20
sei_frame_interval_vencLevel1 = 20
sei_frame_interval_vencLevel2 = 200

#audio
pcm_chn_cnt = 1 #0: disable audio.
pcm_bit_width = 16
pcm_sample_rate = 16000
ai_volume = 90
aec_en = 1
aec_nlp_mode = 1 #0,1,2, kAecNlpConservative, kAecNlpModerate, kAecNlpAggressive
ans_en = 1
ans_mode = 1
agc_en = 1
agc_target_db = 0
agc_max_gain_db = 30
audio_codec_type = "aac" #aac, mp3, pcm, g711a, g711u
bitRate = 32000 #unit:bps

test_duration = 60   #total test time. unit:s, 0 means infinite.

