########### paramter (ref to tulip_cedarx.conf)############
[parameter]

# common configure
test_duration = 30  # unit: s, 0 means infinite

# record configure
record_enable = 1
record_vipp_id = 0
record_online_en = 0
record_online_share_buf_num = 1
record_vipp_buf_num = 3
record_vipp_pixformat = "aw_lbc_2_5x"       # pic_format, such as yu12, yv12, nv21, nv12, nv21s, aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_1_0x
record_vipp_capture_width = 1920
record_vipp_capture_height = 1080
record_vipp_frame_rate = 20     # unit: fps
record_dest_file = "/mnt/extsd/record.raw"
record_video_frame_rate = 20    # unit: fps
record_video_bitrate = 1048576  # unit: bps
record_video_width = 1920
record_video_heigth = 1080
record_video_encoder_type = "H.264"  # H.264, H.265, MJPEG
record_video_rc_mode = 1        # rc_mode for H264/H265 0:CBR, 1:VBR, 2:FIXQP, 3:QPMAP
record_video_duration = 30      # unit: s, per output media file time

# record sub configure
record_sub_enable = 1
record_sub_vipp_id = 4
record_sub_vipp_buf_num = 3
record_sub_vipp_pixformat = "aw_lbc_2_5x"       # pic_format, such as yu12, yv12, nv21, nv12, nv21s, aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_1_0x
record_sub_vipp_capture_width = 640
record_sub_vipp_capture_height = 360
record_sub_vipp_frame_rate = 20     # unit: fps
record_sub_dest_file = "/mnt/extsd/record_sub.raw"
record_sub_video_frame_rate = 20    # unit: fps
record_sub_video_bitrate = 262144   # unit: bps
record_sub_video_width = 640
record_sub_video_heigth = 360
record_sub_video_encoder_type = "H.264"  # H.264, H.265, MJPEG
record_sub_video_rc_mode = 1        # rc_mode for H264/H265 0:CBR, 1:VBR, 2:FIXQP, 3:QPMAP
record_sub_video_duration = 30      # unit: s, per output media file time

# play configure
play_enable = 1
play_video_decoder_type = "JPEG"  # H.264, MJPEG, JPEG
play_src_file = "/mnt/extsd/test.jpg"
play_src_len_file = "/mnt/extsd/vbs.len"    # only for H.264, MJPEG
play_frame_rate = 20
play_vdec_width = 1280
play_vdec_height = 720
play_vdec_buf_size = 0
play_vdec_pixformat = "nv21"
play_vo_dev_id = 0
play_vo_display_x = 0
play_vo_display_y = 0
play_vo_display_width = 720
play_vo_display_height = 1280
play_vo_layer_num = 0          # video layer: layer 0~7, and the attr of 0~3 and 4~7 layers need to be consistent respectively.
play_vo_disp_type = "lcd"

