[parameter]
pic_format = "nv21"
dst_format = "nv21"
src_width = 1920
src_height = 1080
src_rect_x = 0
src_rect_y = 0
src_rect_w = 1920
src_rect_h = 80
dst_rotate = 0 #0, 90, 180, 270, clock-wise.
dst_flip   = " "   #H=horizontal flip, V=vertical flip, N=none
dst_width = 1280
dst_height = 1600
dst_rect_x = 0
dst_rect_y = 880
dst_rect_w = 1280
dst_rect_h = 80

yuv_src_file = "./board_1920x1080.nv21"
yuv_dst_file = "./test2.yuv"

g2d_mod = 0

g2d_bld_mod = 0
