########### paramter (ref to tulip_cedarx.conf)############
[parameter]
dev_num_0 = 0
isp_dev_num_0 = 0
pic_width_0 = 1920
pic_height_0 = 1080
frame_rate_0 = 15
pic_format_0 = "aw_lbc_2_5x"
color_space_0 = "rec709_part_range"
enable_wdr_mode_0 = 0
drop_frm_num_0 = 0
tdm_spdn_en_0 = 0	  # 0: default, disable, 1: enable tdm speed down, must be enable CONFIG_SUPPORT_ISP_TDM for kernel
stitch_mode_0 = DMA_STITCH_2IN1_LINNER     # 0: DMA_STITCH_NONE, 1: DMA_STITCH_2IN1_LINNER, 2: DMA_STITCH_HORIZONTAL, 3: DMA_STITCH_VERTICAL
mipi_pixel_num_0 = 0  # 0: MIPI_ONE_PIXEL, 1: MIPI_TWO_PIXEL(only mipi 4lane can set MIPI_TWO_PIXEL)
dma_overlay_en_0 = 0  # only DMA_STITCH_VERTICAL can do it and pic_format should set nv21 or nv12
dma_overlay_width_0 = 1920
dma_overlay_height_0 = 336
dma_merge_scaler_en_0 = 0
sensorA_width_0 = 0
sensorA_height_0 = 0
sensorB_width_0 = 0
sensorB_height_0 = 0
isp_test_enable_0 = 0
isp_test_interv_ms_0 = 2000
detect_mipi_desk_en_0 = 0
detect_mipi_interv_ms_0 = 1000
detect_mipi_channel_0 = 0     # MIPI0/MIPIA: 0, MIPI1/MIPIB: 1

dev_num_1 = -1
isp_dev_num_1 = 1
pic_width_1 = 1920
pic_height_1 = 1088
frame_rate_1 = 15
pic_format_1 = "aw_lbc_2_5x"
color_space_1 = "rec709_part_range"
enable_wdr_mode_1 = 0
drop_frm_num_1 = 0
tdm_spdn_en_1 = 0
stitch_mode_1 = 0
mipi_pixel_num_1 = 0
dma_overlay_en_1 = 0
dma_overlay_width_1 = 1920
dma_overlay_height_1 = 328
dma_merge_scaler_en_1 = 0
sensorA_width_1 = 0
sensorA_height_1 = 0
sensorB_width_1 = 0
sensorB_height_1 = 0
isp_test_enable_1 = 0
isp_test_interv_ms_1 = 2000

dev_num_2 = -1
isp_dev_num_2 = 1
pic_width_2 = 720
pic_height_2 = 1152
frame_rate_2 = 15
pic_format_2 = "nv21"
color_space_2 = "rec709_part_range"
enable_wdr_mode_2 = 0
drop_frm_num_2 = 0
tdm_spdn_en_2 = 0
stitch_mode_2 = 0
mipi_pixel_num_2 = 0
dma_overlay_en_2 = 0
dma_overlay_width_2 = 1920
dma_overlay_height_2 = 328
dma_merge_scaler_en_2 = 1
sensorA_width_2 = 720
sensorA_height_2 = 744
sensorB_width_2 = 720
sensorB_height_2 = 408

dev_num_3 = -1
isp_dev_num_3 = 1
pic_width_3 = 1920
pic_height_3 = 3088
frame_rate_3 = 20
pic_format_3 = "nv21"
color_space_3 = "rec709_part_range"
enable_wdr_mode_3 = 0
drop_frm_num_3 = 0
tdm_spdn_en_3 = 0
stitch_mode_3 = 0
mipi_pixel_num_4 = 0
dma_overlay_en_3 = 0
dma_overlay_width_3 = 1920
dma_overlay_height_3 = 328
dma_merge_scaler_en_3 = 0
sensorA_width_3 = 0
sensorA_height_3 = 0
sensorB_width_3 = 0
sensorB_height_3 = 0

save_pic_dev = 0
yuv_frm_count = 0
yuv_file = "/mnt/extsd"

raw_store_count = 3
raw_store_interval = 30
store_dir = "/mnt/extsd"

save_pic_buffer_len = 0    # 0: Specify the buffer length according to the pixel and resolution.
save_pic_buffer_num = 3

test_duration = 10
