########### paramter (ref to tulip_cedarx.conf)############
[parameter]
yuv_file_path = "/mnt/extsd/"

vdecoder_format = "h264" #jpeg, h264, h265

# 0:default decided by libcedarc, unit:Bytes
vdec_buf_size = 0

# Normal: nv21(yvu420sp), yu12(yuv420p), yv12, nv12
# LBC: aw_lbc_2_0x, aw_lbc_2_5x, aw_lbc_1_5x, aw_lbc_1_0x
video_pixfmt = "nv21"

#vdec max output frame width and height, 0:unlimited
vdec_max_width = 0
vdec_max_height = 0

# video raw stream requires a specified resolution(default: 1920*1080), 0:unknown
video_width = 0
video_height = 0

# for jpeg, jpeg_num >= 1
# jpeg_num = 1 (one jpeg picture): test.jpg
# jpeg_num > 1 (multi jpeg pictures): pic0.jpg pic1.jpg pic2.jpg pic3.jpg ...
jpeg_num = 1
jpeg_one_file_path = "/mnt/extsd/test.jpg"
jpeg_multi_file_path = "/mnt/extsd/pic"

# for h264
h264_vbs_path = "/mnt/extsd/vbs.h264"
h264_len_path = "/mnt/extsd/vbs.len"

# for h265
h265_vbs_path = "/mnt/extsd/vbs.h265"
h265_len_path = "/mnt/extsd/vbs.len"
