########### paramter (ref to tulip_cedarx.conf)############
  [parameter]
venc_vaild = 1
venc_vipp_dev = 0
venc_capture_width = 1920
venc_capture_height = 1080
venc_display_width = 1920
venc_display_height = 1080
venc_encode_type = "H.265" 
venc_file_path = "/mnt/sdcard/venc_stream.raw"

preview_vipp_dev = 4
preview_capture_width = 1280
preview_capture_height = 720
preview_layer_num = 4
preview_display_x = 0
preview_display_y = 0
preview_display_width = 1280
preview_display_height = 720

npu_vipp_dev = 8    
npu_nbg_file_path = "/mnt/sdcard/network_binary.nb"

test_duration = 60 #unit:s, 0:Infinite duration.